#!/usr/bin/env python3
"""build_words.py — generate data/words.json for the Latin flashcards app.

Source of truth for the CORE deck list: ../kana-flashcards/data/words.json
(the family's 592-meaning Japanese list — Mike: "same list ideally").
This script ORACLE-asserts that every English gloss in that file is covered
exactly once (duplicates consumed positionally), so list drift = hard failure.

Latin conventions:
  - nouns cited nom. + gen. ending, gram = gender + declension ("f1", "m3"...)
  - verbs cited 1sg + infinitive, gram = conjugation ("v1".."v4", "v3io", "dep", "irr")
  - adjectives cited m/f/n, gram = "adj12" (us/a/um) or "adj3"
  - macrons everywhere (long marks are load-bearing for homeschool Latin)
  - neo=1 → post-antique coinage (modern thing; no classical word exists)
"""
import json, sys, os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'kana-flashcards', 'data', 'words.json')

# en gloss -> list of (latin, gram, neo, note) consumed IN ORDER of appearance.
M = {
 "adjective": [("nōmen adiectīvum", "n3 phrase", 0, "grammar term")],
 "adult": [("adultus, -ī", "m2", 0, "")],
 "afternoon": [("tempus pomerīdiānum", "n3 phrase", 0, "post merīdiem = after midday")],
 "air": [("āēr, āeris", "m3", 0, "Greek loan")],
 "airport": [("āeriportus, -ūs", "m4", 1, "")],
 "alive": [("vīvus, -a, -um", "adj12", 0, "")],
 "animal": [("animal, -ālis", "n3", 0, "")],
 "apartment": [("īnsula, -ae", "f1", 0, "Roman apartment block — same word as island!")],
 "apple": [("mālum, -ī", "n2", 0, "mālum apple vs malum evil — macron matters")],
 "april": [("Aprīlis, -is", "m3", 0, "")],
 "hand": [("manus, -ūs", "f4", 0, "feminine! 4th decl.")],
 "army": [("exercitus, -ūs", "m4", 0, "")],
 "art": [("ars, artis", "f3", 0, "")],
 "artist": [("artifex, -ficis", "m/f3", 0, "")],
 "august": [("Augustus, -ī", "m2", 0, "named for Emperor Augustus")],
 "author": [("auctor, -ōris", "m3", 0, "root of 'authority'")],
 "baby": [("īnfāns, -antis", "m/f3", 0, "lit. 'not speaking'")],
 "back": [("tergum, -ī", "n2", 0, "the body part"),
          ("retrō", "adv", 0, "backwards — as in retrograde")],
 "bad": [("malus, -a, -um", "adj12", 0, "")],
 "bag": [("saccus, -ī", "m2", 0, "")],
 "ball": [("pila, -ae", "f1", 0, "")],
 "banana": [("ariēna, -ae", "f1", 0, "attested in Pliny!")],
 "band": [("grex mūsicus", "m3 phrase", 1, "grex = flock/troop (classical)")],
 "bank": [("argentāria, -ae", "f1", 0, "from argentum, silver")],
 "bathroom": [("balneum, -ī", "n2", 0, "Romans loved baths")],
 "beach": [("lītus, -oris", "n3", 0, "")],
 "beard": [("barba, -ae", "f1", 0, "root of 'barber'")],
 "beautiful": [("pulcher, -chra, -chrum", "adj12", 0, "")],
 "bed": [("lectus, -ī", "m2", 0, "")],
 "bedroom": [("cubiculum, -ī", "n2", 0, "")],
 "beef": [("bubula, -ae", "f1", 0, "carō bubula, cow-meat")],
 "beer": [("cervēsia, -ae", "f1", 0, "Gaulish loan — cf. Spanish cerveza")],
 "beverage": [("pōtiō, -ōnis", "f3", 0, "root of 'potion'")],
 "bicycle": [("birota, -ae", "f1", 1, "lit. 'two-wheel'")],
 "big": [("magnus, -a, -um", "adj12", 0, "")],
 "bill": [("ratiō, -ōnis", "f3", 0, "account/reckoning")],
 "billion": [("mīliardum", "num", 1, "")],
 "bird": [("avis, -is", "f3", 0, "as in aviary")],
 "black": [("niger, -gra, -grum", "adj12", 0, "")],
 "blindess": [("caecitās, -ātis", "f3", 0, "")],
 "blood": [("sanguis, -inis", "m3", 0, "")],
 "blue": [("caeruleus, -a, -um", "adj12", 0, "from caelum, sky")],
 "boat": [("nāvicula, -ae", "f1", 0, "little ship")],
 "body": [("corpus, -oris", "n3", 0, "")],
 "bone": [("os, ossis", "n3", 0, "short o — vs ōs, ōris mouth!")],
 "book": [("liber, librī", "m2", 0, "as in library")],
 "bottle": [("lagoena, -ae", "f1", 0, "")],
 "bottom": [("fundus, -ī", "m2", 0, "as in 'fundamental'")],
 "box": [("arca, -ae", "f1", 0, "as in Noah's ark")],
 "boy": [("puer, puerī", "m2", 0, "")],
 "brain": [("cerebrum, -ī", "n2", 0, "")],
 "bread": [("pānis, -is", "m3", 0, "cf. companion = bread-sharer")],
 "breakfast": [("ientāculum, -ī", "n2", 0, "")],
 "bridge": [("pōns, pontis", "m3", 0, "as in pontoon")],
 "(older) brother": [("frāter nātū maior", "m3 phrase", 0, "greater by birth")],
 "(little) brother": [("frāter nātū minor", "m3 phrase", 0, "lesser by birth")],
 "brown": [("fuscus, -a, -um", "adj12", 0, "")],
 "building": [("aedificium, -ī", "n2", 0, "as in edifice")],
 "bus": [("raeda pūblica", "f1 phrase", 1, "raeda = classical carriage")],
 "cake": [("placenta, -ae", "f1", 0, "yes, really — Roman flat cake")],
 "camera": [("māchina photographica", "f1 phrase", 1, "")],
 "camp": [("castra, -ōrum", "n2 pl", 0, "-chester/-caster place names")],
 "car": [("autoraeda, -ae", "f1", 1, "")],
 "card": [("chartula, -ae", "f1", 0, "little paper")],
 "cat": [("fēlēs, -is", "f3", 0, "as in feline")],
 "ceiling": [("lacūnar, -āris", "n3", 0, "")],
 "cell phone": [("tēlephōnum gestābile", "n2 phrase", 1, "carryable telephone")],
 "centimeter": [("centimetrum, -ī", "n2", 1, "")],
 "chair": [("sella, -ae", "f1", 0, "")],
 "cheap": [("vīlis, -e", "adj3", 0, "as in vile")],
 "cheese": [("cāseus, -ī", "m2", 0, "cf. queso, Käse")],
 "chicken": [("pullus, -ī", "m2", 0, "as in poultry")],
 "child": [("puer, puerī", "m2", 0, "līberī = children (pl.)")],
 "church": [("ecclēsia, -ae", "f1", 0, "Greek loan")],
 "circle": [("circulus, -ī", "m2", 0, "")],
 "city": [("urbs, urbis", "f3", 0, "as in urban")],
 "clay": [("argilla, -ae", "f1", 0, "")],
 "clock": [("hōrologium, -ī", "n2", 0, "hour-teller")],
 "clothes": [("vestīmenta, -ōrum", "n2 pl", 0, "as in vestments")],
 "club": [("sodālitās, -ātis", "f3", 0, "fellowship")],
 "coat": [("paenula, -ae", "f1", 0, "Roman travel cloak")],
 "coffee": [("caffēum, -ī", "n2", 1, "")],
 "cold": [("frīgidus, -a, -um", "adj12", 0, "as in frigid")],
 "color": [("color, -ōris", "m3", 0, "")],
 "computer": [("computātrum, -ī", "n2", 1, "from computō, reckon")],
 "consonant": [("cōnsonāns, -antis", "f3", 0, "grammar term")],
 "contract": [("pactum, -ī", "n2", 0, "as in pact")],
 "copper": [("aes, aeris", "n3", 0, "copper/bronze")],
 "coin": [("nummus, -ī", "m2", 0, "")],
 "corn": [("frūmentum, -ī", "n2", 0, "grain")],
 "corner": [("angulus, -ī", "m2", 0, "as in angle")],
 "country": [("patria, -ae", "f1", 0, "fatherland — as in patriot")],
 "court": [("iūdicium, -ī", "n2", 0, "as in judicial")],
 "cow": [("vacca, -ae", "f1", 0, "as in vaccine (cowpox!)")],
 "cup": [("pōculum, -ī", "n2", 0, "")],
 "curved": [("curvus, -a, -um", "adj12", 0, "")],
 "dark": [("obscūrus, -a, -um", "adj12", 0, "")],
 "daughter": [("fīlia, -ae", "f1", 0, "as in filial")],
 "day": [("diēs, diēī", "m5", 0, "5th declension")],
 "deaf person": [("surdus, -ī", "m2", 0, "as in absurd")],
 "december": [("December, -bris", "m3", 0, "10th month of old calendar")],
 "diamond": [("adamās, -antis", "m3", 0, "as in adamant — unconquerable")],
 "dinner": [("cēna, -ae", "f1", 0, "")],
 "direction": [("regiō, -ōnis", "f3", 0, "as in region")],
 "dirty": [("sordidus, -a, -um", "adj12", 0, "as in sordid")],
 "disease": [("morbus, -ī", "m2", 0, "as in morbid")],
 "doctor": [("medicus, -ī", "m2", 0, "")],
 "dog": [("canis, -is", "m/f3", 0, "as in canine")],
 "dollar": [("dollarium, -ī", "n2", 1, "")],
 "door": [("iānua, -ae", "f1", 0, "from Janus, god of doorways")],
 "dot": [("pūnctum, -ī", "n2", 0, "as in punctuation")],
 "down": [("deorsum", "adv", 0, "")],
 "dream": [("somnium, -ī", "n2", 0, "as in insomnia")],
 "dress": [("stola, -ae", "f1", 0, "Roman matron's dress")],
 "drug": [("medicāmentum, -ī", "n2", 0, "")],
 "dry": [("siccus, -a, -um", "adj12", 0, "as in desiccated")],
 "dust": [("pulvis, -eris", "m3", 0, "as in pulverize")],
 "ear": [("auris, -is", "f3", 0, "as in aural")],
 "east": [("oriēns, -entis", "m3", 0, "the rising (sun)")],
 "edge": [("margō, -inis", "m3", 0, "as in margin")],
 "egg": [("ōvum, -ī", "n2", 0, "as in oval")],
 "eight": [("octō", "num", 0, "")],
 "eighteen": [("duodēvīgintī", "num", 0, "two-from-twenty")],
 "eighty": [("octōgintā", "num", 0, "")],
 "electronic device": [("īnstrūmentum ēlectronicum", "n2 phrase", 1, "")],
 "eleven": [("ūndecim", "num", 0, "")],
 "engine": [("māchina, -ae", "f1", 0, "")],
 "evening": [("vesper, -erī", "m2", 0, "as in vespers")],
 "expensive": [("cārus, -a, -um", "adj12", 0, "also 'dear'")],
 "eye": [("oculus, -ī", "m2", 0, "as in ocular")],
 "face": [("faciēs, -ēī", "f5", 0, "5th declension")],
 "family": [("familia, -ae", "f1", 0, "the whole household")],
 "famous": [("clārus, -a, -um", "adj12", 0, "bright/famous")],
 "electric fan": [("flābellum ēlectricum", "n2 phrase", 1, "flābellum = classical hand fan")],
 "farm": [("praedium, -ī", "n2", 0, "")],
 "fast": [("celer, -eris, -ere", "adj3", 0, "as in accelerate")],
 "father": [("pater, patris", "m3", 0, "as in paternal")],
 "february": [("Februārius, -ī", "m2", 0, "month of purification")],
 "female": [("fēmineus, -a, -um", "adj12", 0, "")],
 "fifteen": [("quīndecim", "num", 0, "")],
 "fifty": [("quīnquāgintā", "num", 0, "")],
 "finger": [("digitus, -ī", "m2", 0, "as in digit")],
 "fire": [("ignis, -is", "m3", 0, "as in ignite")],
 "fish": [("piscis, -is", "m3", 0, "as in Pisces")],
 "floor": [("pavīmentum, -ī", "n2", 0, "as in pavement")],
 "flower": [("flōs, flōris", "m3", 0, "as in floral")],
 "food": [("cibus, -ī", "m2", 0, "")],
 "forest": [("silva, -ae", "f1", 0, "as in Pennsylvania")],
 "fork": [("furca, -ae", "f1", 0, "")],
 "fourty": [("quadrāgintā", "num", 0, "")],
 "four": [("quattuor", "num", 0, "")],
 "fourteen": [("quattuordecim", "num", 0, "")],
 "friday": [("diēs Veneris", "m5 phrase", 0, "day of Venus — cf. French vendredi")],
 "friend": [("amīcus, -ī", "m2", 0, "from amō, love")],
 "front": [("frōns, frontis", "f3", 0, "")],
 "game": [("lūdus, -ī", "m2", 0, "game AND school!")],
 "garden": [("hortus, -ī", "m2", 0, "as in horticulture")],
 "gasoline": [("benzīnum, -ī", "n2", 1, "")],
 "gift": [("dōnum, -ī", "n2", 0, "as in donate")],
 "girl": [("puella, -ae", "f1", 0, "")],
 "paper": [("charta, -ae", "f1", 0, "as in chart, card")],
 "gold": [("aurum, -ī", "n2", 0, "symbol Au!")],
 "good": [("bonus, -a, -um", "adj12", 0, "")],
 "grandfather": [("avus, -ī", "m2", 0, "")],
 "grandmother": [("avia, -ae", "f1", 0, "")],
 "grass": [("herba, -ae", "f1", 0, "as in herb")],
 "gray": [("cānus, -a, -um", "adj12", 0, "gray-haired")],
 "green": [("viridis, -e", "adj3", 0, "as in verdant")],
 "ground": [("humus, -ī", "f2", 0, "feminine! as in humble, exhume")],
 "gun": [("sclopētum, -ī", "n2", 1, "")],
 "hair": [("capillus, -ī", "m2", 0, "as in capillary")],
 "half": [("dīmidium, -ī", "n2", 0, "")],
 "happy": [("laetus, -a, -um", "adj12", 0, "")],
 "hard": [("dūrus, -a, -um", "adj12", 0, "as in durable")],
 "hat": [("petasus, -ī", "m2", 0, "traveler's hat — Mercury wears one")],
 "head": [("caput, capitis", "n3", 0, "as in capital")],
 "healthy": [("sānus, -a, -um", "adj12", 0, "as in sane")],
 "heart": [("cor, cordis", "n3", 0, "as in cordial, courage")],
 "fever": [("febris, -is", "f3", 0, "")],
 "heaven": [("paradīsus, -ī", "m2", 0, "caelum = sky/heaven too")],
 "heavy": [("gravis, -e", "adj3", 0, "as in gravity")],
 "hell": [("īnfernus, -ī", "m2", 0, "as in infernal")],
 "hill": [("collis, -is", "m3", 0, "Rome's seven hills: septem collēs")],
 "hole": [("forāmen, -inis", "n3", 0, "")],
 "horse": [("equus, -ī", "m2", 0, "as in equestrian")],
 "hospital": [("valētūdinārium, -ī", "n2", 0, "real Roman army hospitals")],
 "hot": [("calidus, -a, -um", "adj12", 0, "cf. scald, cauldron")],
 "hotel": [("dēversōrium, -ī", "n2", 0, "Roman roadside inn")],
 "hour": [("hōra, -ae", "f1", 0, "")],
 "house": [("domus, -ūs", "f4", 0, "as in domestic")],
 "human": [("homō, hominis", "m3", 0, "as in Homō sapiēns")],
 "hundred": [("centum", "num", 0, "as in century, percent")],
 "husband": [("marītus, -ī", "m2", 0, "as in marital")],
 "ice": [("glaciēs, -ēī", "f5", 0, "as in glacier")],
 "image": [("imāgō, -inis", "f3", 0, "")],
 "inch": [("ūncia, -ae", "f1", 0, "a twelfth — also 'ounce'!")],
 "injury": [("vulnus, -eris", "n3", 0, "as in vulnerable")],
 "inside": [("intus", "adv", 0, "")],
 "island": [("īnsula, -ae", "f1", 0, "as in insulate, peninsula")],
 "january": [("Iānuārius, -ī", "m2", 0, "Janus — looks both ways")],
 "job": [("opus, operis", "n3", 0, "as in opera, operate")],
 "juice": [("sūcus, -ī", "m2", 0, "cf. succulent")],
 "july": [("Iūlius, -ī", "m2", 0, "named for Julius Caesar")],
 "june": [("Iūnius, -ī", "m2", 0, "month of Juno")],
 "key": [("clāvis, -is", "f3", 0, "as in clavicle, clef")],
 "kilogram": [("chīliogramma, -atis", "n3", 1, "")],
 "king": [("rēx, rēgis", "m3", 0, "as in regal — Henle word")],
 "kitchen": [("culīna, -ae", "f1", 0, "as in culinary")],
 "knee": [("genū, -ūs", "n4", 0, "as in genuflect")],
 "knife": [("culter, -trī", "m2", 0, "")],
 "lake": [("lacus, -ūs", "m4", 0, "as in lagoon")],
 "lamp": [("lucerna, -ae", "f1", 0, "from lūx, light")],
 "laptop": [("computātrum portābile", "n2 phrase", 1, "")],
 "lawyer": [("advocātus, -ī", "m2", 0, "one called to your side")],
 "leaf": [("folium, -ī", "n2", 0, "as in foliage, portfolio")],
 "lemon": [("cītreum, -ī", "n2", 0, "citrus fruit")],
 "library": [("bibliothēca, -ae", "f1", 0, "Greek loan")],
 "light": [("lūx, lūcis", "f3", 0, "as in lucid — fiat lūx!"),
           ("levis, -e", "adj3", 0, "not heavy — as in levity, elevate"),
           ("lūcidus, -a, -um", "adj12", 0, "bright")],
 "lips": [("labra, -ōrum", "n2 pl", 0, "")],
 "location": [("locus, -ī", "m2", 0, "as in local")],
 "loose": [("laxus, -a, -um", "adj12", 0, "as in relax")],
 "loud": [("clāmōsus, -a, -um", "adj12", 0, "as in clamor")],
 "lunch": [("prandium, -ī", "n2", 0, "")],
 "magazine": [("libellus periodicus", "m2 phrase", 1, "little periodic book")],
 "male": [("māsculus, -a, -um", "adj12", 0, "")],
 "man": [("vir, virī", "m2", 0, "as in virtue — Henle word")],
 "manager": [("prōcūrātor, -ōris", "m3", 0, "a real Roman job")],
 "map": [("tabula geōgraphica", "f1 phrase", 1, "")],
 "march": [("Mārtius, -ī", "m2", 0, "month of Mars")],
 "(town) market": [("forum, -ī", "n2", 0, "THE Roman market square")],
 "marriage": [("mātrimōnium, -ī", "n2", 0, "")],
 "material": [("māteria, -ae", "f1", 0, "")],
 "may": [("Māius, -ī", "m2", 0, "month of Maia")],
 "mean spirited": [("malignus, -a, -um", "adj12", 0, "as in malign")],
 "medicine": [("medicīna, -ae", "f1", 0, "")],
 "metal": [("metallum, -ī", "n2", 0, "")],
 "meter": [("metrum, -ī", "n2", 1, "as unit of length")],
 "milk": [("lac, lactis", "n3", 0, "as in lactose")],
 "one million": [("mīliō, -ōnis", "m3", 1, "")],
 "minute": [("minūtum, -ī", "n2", 0, "medieval Latin")],
 "monday": [("diēs Lūnae", "m5 phrase", 0, "day of the Moon")],
 "money": [("pecūnia, -ae", "f1", 0, "from pecus, cattle — wealth on the hoof")],
 "moon": [("lūna, -ae", "f1", 0, "as in lunar")],
 "morning": [("māne", "n indecl", 0, "")],
 "mother": [("māter, mātris", "f3", 0, "as in maternal")],
 "mountain": [("mōns, montis", "m3", 0, "as in Montana")],
 "mouse": [("mūs, mūris", "m3", 0, "as in muscle — 'little mouse'")],
 "mouth": [("ōs, ōris", "n3", 0, "long ō — vs os, ossis bone!")],
 "movie": [("pellīcula, -ae", "f1", 1, "little skin → film")],
 "murder": [("homicīdium, -ī", "n2", 0, "")],
 "music": [("mūsica, -ae", "f1", 0, "art of the Muses")],
 "narrow": [("angustus, -a, -um", "adj12", 0, "as in anguish")],
 "nature": [("nātūra, -ae", "f1", 0, "")],
 "neck": [("collum, -ī", "n2", 0, "as in collar")],
 "needle": [("acus, -ūs", "f4", 0, "as in acute")],
 "neighbor": [("vīcīnus, -ī", "m2", 0, "as in vicinity")],
 "network": [("rēte, -is", "n3", 0, "net — the internet is rēte ūniversāle")],
 "new": [("novus, -a, -um", "adj12", 0, "as in novel")],
 "newspaper": [("ācta diūrna", "n2 pl", 0, "Caesar's actual daily gazette")],
 "nice": [("suāvis, -e", "adj3", 0, "as in suave")],
 "nine": [("novem", "num", 0, "as in November")],
 "nineteen": [("ūndēvīgintī", "num", 0, "one-from-twenty")],
 "ninety": [("nōnāgintā", "num", 0, "")],
 "no": [("minimē", "adv", 0, "lit. 'least of all'")],
 "north": [("septentriō, -ōnis", "m3", 0, "the seven plow-oxen (Big Dipper)")],
 "nose": [("nāsus, -ī", "m2", 0, "as in nasal")],
 "november": [("November, -bris", "m3", 0, "9th month of old calendar")],
 "nuclear": [("nucleāris, -e", "adj3", 1, "from nucleus, kernel")],
 "number": [("numerus, -ī", "m2", 0, "")],
 "ocean": [("ōceanus, -ī", "m2", 0, "Greek loan")],
 "october": [("Octōber, -bris", "m3", 0, "8th month of old calendar")],
 "office": [("tablīnum, -ī", "n2", 0, "the Roman home office")],
 "one": [("ūnus, -a, -um", "num", 0, "as in unite")],
 "orange": [("mālum aurantium", "n2 phrase", 1, "the fruit"),
            ("aurantius, -a, -um", "adj12", 1, "the color")],
 "outside": [("forīs", "adv", 0, "as in foreign")],
 "page": [("pāgina, -ae", "f1", 0, "")],
 "pain": [("dolor, -ōris", "m3", 0, "as in dolorous")],
 "paint": [("pigmentum, -ī", "n2", 0, "as in pigment")],
 "parent": [("parēns, -entis", "m/f3", 0, "")],
 "patient": [("aegrōtus, -ī", "m2", 0, "sick person")],
 "pattern": [("exemplar, -āris", "n3", 0, "")],
 "peace": [("pāx, pācis", "f3", 0, "Pāx Rōmāna")],
 "pen": [("stilus, -ī", "m2", 0, "as in style")],
 "pencil": [("graphis, -idis", "f3", 0, "as in graphite")],
 "person": [("persōna, -ae", "f1", 0, "originally an actor's mask")],
 "photograph": [("phōtographēma, -atis", "n3", 1, "")],
 "pig": [("porcus, -ī", "m2", 0, "as in pork")],
 "pink": [("roseus, -a, -um", "adj12", 0, "rose-colored")],
 "plane": [("āeroplānum, -ī", "n2", 1, "")],
 "plant": [("planta, -ae", "f1", 0, "")],
 "plastic": [("plasticum, -ī", "n2", 1, "")],
 "plate": [("patella, -ae", "f1", 0, "also your kneecap!")],
 "pocket": [("loculus, -ī", "m2", 0, "little place")],
 "poison": [("venēnum, -ī", "n2", 0, "as in venom")],
 "police": [("vigilēs, -um", "m3 pl", 0, "Rome's real night watch")],
 "pool": [("piscīna, -ae", "f1", 0, "originally a fish pond")],
 "poor": [("pauper, -eris", "adj3", 0, "as in poverty")],
 "pork": [("porcīna, -ae", "f1", 0, "carō porcīna")],
 "president": [("praeses, -idis", "m3", 0, "one who sits before")],
 "price": [("pretium, -ī", "n2", 0, "as in precious")],
 "priest": [("sacerdōs, -ōtis", "m/f3", 0, "as in sacred")],
 "prison": [("carcer, -eris", "m3", 0, "as in incarcerate")],
 "queen": [("rēgīna, -ae", "f1", 0, "Henle word")],
 "quiet": [("quiētus, -a, -um", "adj12", 0, "")],
 "radio": [("radiophōnum, -ī", "n2", 1, "")],
 "rain": [("pluvia, -ae", "f1", 0, "cf. pluvial")],
 "red": [("ruber, -bra, -brum", "adj12", 0, "as in ruby")],
 "religion": [("religiō, -ōnis", "f3", 0, "")],
 "reporter": [("diurnārius, -ī", "m2", 1, "from ācta diūrna")],
 "restaurant": [("caupōna, -ae", "f1", 0, "Roman tavern")],
 "rice": [("orȳza, -ae", "f1", 0, "attested in Horace")],
 "rich": [("dīves, -itis", "adj3", 0, "")],
 "ring": [("ānulus, -ī", "m2", 0, "as in annular")],
 "river": [("flūmen, -inis", "n3", 0, "as in flume")],
 "roof": [("tēctum, -ī", "n2", 0, "as in protect — covered over")],
 "root": [("rādīx, -īcis", "f3", 0, "as in radical, radish")],
 "sad": [("trīstis, -e", "adj3", 0, "")],
 "salt": [("sāl, salis", "m3", 0, "as in salary — soldiers' salt money")],
 "sand": [("harēna, -ae", "f1", 0, "the arena was sand-floored")],
 "saturday": [("diēs Sāturnī", "m5 phrase", 0, "day of Saturn")],
 "school": [("schola, -ae", "f1", 0, "orig. 'leisure' in Greek!")],
 "science": [("scientia, -ae", "f1", 0, "from sciō, know")],
 "screen": [("vīsōrium, -ī", "n2", 1, "from vīsus, sight")],
 "sea": [("mare, -is", "n3", 0, "as in marine — Henle word")],
 "season": [("tempus annī", "n3 phrase", 0, "time of the year")],
 "secretary": [("scrība, -ae", "m1", 0, "masculine 1st declension!")],
 "seed": [("sēmen, -inis", "n3", 0, "as in disseminate")],
 "september": [("September, -bris", "m3", 0, "7th month of old calendar")],
 "seven": [("septem", "num", 0, "")],
 "seventeen": [("septendecim", "num", 0, "")],
 "seventy": [("septuāgintā", "num", 0, "")],
 "shallow": [("vadōsus, -a, -um", "adj12", 0, "full of shallows")],
 "ship": [("nāvis, -is", "f3", 0, "as in navy")],
 "shirt": [("tunica, -ae", "f1", 0, "")],
 "shoes": [("calceī, -ōrum", "m2 pl", 0, "")],
 "shoulder": [("umerus, -ī", "m2", 0, "")],
 "side": [("latus, -eris", "n3", 0, "as in lateral — short a vs lātus wide")],
 "sign": [("signum, -ī", "n2", 0, "")],
 "silver": [("argentum, -ī", "n2", 0, "symbol Ag — Argentina!")],
 "(older) sister": [("soror nātū maior", "f3 phrase", 0, "")],
 "(little) sister": [("soror nātū minor", "f3 phrase", 0, "")],
 "six": [("sex", "num", 0, "")],
 "sixteen": [("sēdecim", "num", 0, "")],
 "sixty": [("sexāgintā", "num", 0, "")],
 "skin": [("cutis, -is", "f3", 0, "as in cuticle")],
 "skirt": [("gunna, -ae", "f1", 1, "medieval Latin — cf. 'gown'")],
 "sky": [("caelum, -ī", "n2", 0, "as in celestial")],
 "slow": [("tardus, -a, -um", "adj12", 0, "as in tardy")],
 "small": [("parvus, -a, -um", "adj12", 0, "")],
 "snow": [("nix, nivis", "f3", 0, "cf. Nevada")],
 "soap": [("sāpō, -ōnis", "m3", 0, "attested in Pliny")],
 "soft": [("mollis, -e", "adj3", 0, "as in mollify")],
 "soil": [("solum, -ī", "n2", 0, "")],
 "soldier": [("mīles, -itis", "m3", 0, "as in military")],
 "son": [("fīlius, -ī", "m2", 0, "")],
 "song": [("carmen, -inis", "n3", 0, "as in Carmina Burana")],
 "sound": [("sonus, -ī", "m2", 0, "as in sonic")],
 "soup": [("iūs, iūris", "n3", 0, "broth — same word as LAW. Roman joke material")],
 "south": [("merīdiēs, -ēī", "m5", 0, "midday direction")],
 "outerspace": [("spatium cosmicum", "n2 phrase", 1, "")],
 "spoon": [("cochlear, -āris", "n3", 0, "from cochlea, snail shell")],
 "sport": [("athlētica, -ae", "f1", 1, "")],
 "square": [("quadrātum, -ī", "n2", 0, "")],
 "stain": [("macula, -ae", "f1", 0, "as in immaculate — no stain")],
 "star": [("stēlla, -ae", "f1", 0, "as in stellar, constellation")],
 "stone": [("lapis, -idis", "m3", 0, "as in lapidary")],
 "shop": [("taberna, -ae", "f1", 0, "as in tavern")],
 "street": [("via, -ae", "f1", 0, "Via Appia — all roads lead to Rome")],
 "strong": [("fortis, -e", "adj3", 0, "as in fortitude — Henle word")],
 "student": [("discipulus, -ī", "m2", 0, "as in disciple")],
 "sugar": [("saccharum, -ī", "n2", 0, "attested in Pliny")],
 "suit": [("toga, -ae", "f1", 0, "THE Roman formal suit")],
 "summer": [("aestās, -ātis", "f3", 0, "")],
 "sun": [("sōl, sōlis", "m3", 0, "as in solar")],
 "sunday": [("diēs Sōlis", "m5 phrase", 0, "day of the Sun")],
 "sweat": [("sūdor, -ōris", "m3", 0, "")],
 "t-shirt": [("tunicula, -ae", "f1", 1, "little tunic")],
 "table": [("mēnsa, -ae", "f1", 0, "the classic first Latin noun")],
 "tall": [("prōcērus, -a, -um", "adj12", 0, "of persons")],
 "tea": [("thea, -ae", "f1", 1, "")],
 "teacher": [("magister, -trī", "m2", 0, "magistra (f) — as in magistrate")],
 "team": [("turma, -ae", "f1", 0, "Roman cavalry squadron")],
 "teardrop": [("lacrima, -ae", "f1", 0, "as in lacrimose")],
 "technology": [("ars technica", "f3 phrase", 1, "")],
 "telephone": [("tēlephōnum, -ī", "n2", 1, "far-sound")],
 "television": [("tēlevīsiō, -ōnis", "f3", 1, "far-sight")],
 "ten": [("decem", "num", 0, "as in decimal, December")],
 "(movie) theater": [("theātrum, -ī", "n2", 0, "Greek loan")],
 "they": [("eī / eae / ea", "pron", 0, "m / f / n")],
 "thick": [("crassus, -a, -um", "adj12", 0, "as in crass")],
 "thirteen": [("tredecim", "num", 0, "")],
 "thirty": [("trīgintā", "num", 0, "")],
 "thousand": [("mīlle", "num", 0, "as in mile — 1000 paces")],
 "three": [("trēs, tria", "num", 0, "")],
 "thursday": [("diēs Iovis", "m5 phrase", 0, "day of Jupiter — cf. French jeudi")],
 "tight": [("strictus, -a, -um", "adj12", 0, "as in strict")],
 "time": [("tempus, -oris", "n3", 0, "as in temporal")],
 "tongue": [("lingua, -ae", "f1", 0, "tongue AND language")],
 "tool": [("īnstrūmentum, -ī", "n2", 0, "")],
 "tooth": [("dēns, dentis", "m3", 0, "as in dental")],
 "top": [("summum, -ī", "n2", 0, "as in summit")],
 "town": [("oppidum, -ī", "n2", 0, "Henle word")],
 "train": [("trāmen, -inis", "n3", 1, "living-Latin coinage")],
 "train station": [("statiō trāminum", "f3 phrase", 1, "")],
 "transportation": [("vectūra, -ae", "f1", 0, "")],
 "tree": [("arbor, -oris", "f3", 0, "feminine! as in Arbor Day")],
 "truck": [("autocarrum, -ī", "n2", 1, "carrus = classical wagon")],
 "tuesday": [("diēs Mārtis", "m5 phrase", 0, "day of Mars — cf. French mardi")],
 "twelve": [("duodecim", "num", 0, "as in duodecimal")],
 "twenty": [("vīgintī", "num", 0, "")],
 "two": [("duo, duae, duo", "num", 0, "as in dual")],
 "university": [("ūniversitās, -ātis", "f3", 0, "medieval Latin")],
 "up": [("sūrsum", "adv", 0, "")],
 "valley": [("vallēs, -is", "f3", 0, "")],
 "verb": [("verbum, -ī", "n2", 0, "also just 'word'")],
 "victim": [("victima, -ae", "f1", 0, "")],
 "voice": [("vōx, vōcis", "f3", 0, "as in vocal")],
 "vowel": [("vōcālis, -is", "f3", 0, "grammar term")],
 "waiter": [("minister, -trī", "m2", 0, "attendant — as in minister!")],
 "wall": [("mūrus, -ī", "m2", 0, "as in mural")],
 "war": [("bellum, -ī", "n2", 0, "as in belligerent — Henle word")],
 "warm": [("tepidus, -a, -um", "adj12", 0, "as in tepid")],
 "water": [("aqua, -ae", "f1", 0, "as in aquarium — Henle word")],
 "wave": [("unda, -ae", "f1", 0, "as in undulate")],
 "we": [("nōs", "pron", 0, "")],
 "weak": [("īnfīrmus, -a, -um", "adj12", 0, "as in infirmary")],
 "wednesday": [("diēs Mercuriī", "m5 phrase", 0, "day of Mercury — cf. French mercredi")],
 "week": [("hebdomas, -adis", "f3", 0, "Greek loan, late Latin")],
 "weight": [("pondus, -eris", "n3", 0, "as in ponderous")],
 "west": [("occidēns, -entis", "m3", 0, "the falling (sun)")],
 "white": [("albus, -a, -um", "adj12", 0, "as in albino, album")],
 "wide": [("lātus, -a, -um", "adj12", 0, "long ā — vs latus, side")],
 "wife": [("uxor, -ōris", "f3", 0, "")],
 "wind": [("ventus, -ī", "m2", 0, "as in ventilate")],
 "window": [("fenestra, -ae", "f1", 0, "as in defenestrate")],
 "wine": [("vīnum, -ī", "n2", 0, "as in vine")],
 "wing": [("āla, -ae", "f1", 0, "")],
 "winter": [("hiems, hiemis", "f3", 0, "cf. hibernate")],
 "woman": [("fēmina, -ae", "f1", 0, "as in feminine")],
 "wood": [("lignum, -ī", "n2", 0, "")],
 "world": [("mundus, -ī", "m2", 0, "also means 'clean, elegant'!")],
 "year": [("annus, -ī", "m2", 0, "as in annual")],
 "yellow": [("flāvus, -a, -um", "adj12", 0, "")],
 "yes": [("ita vērō", "adv", 0, "'thus truly' — Latin has no single word for yes")],
 "you": [("tū / vōs", "pron", 0, "singular / plural")],
 "young": [("iuvenis, -is", "adj3", 0, "as in juvenile")],
 "zero": [("nihil", "n indecl", 0, "nothing — the numeral came later (zephirum)")],
 "attack (noun": [("impetus, -ūs", "m4", 0, "as in impetuous")],
 "bar": [("taberna vīnāria", "f1 phrase", 0, "wine shop")],
 "to beat": [("pulsō, pulsāre", "v1", 0, "as in pulse")],
 "to bend": [("flectō, flectere", "v3", 0, "as in flexible")],
 "to break": [("frangō, frangere", "v3", 0, "as in fragile, fracture")],
 "to build": [("aedificō, aedificāre", "v1", 0, "as in edifice")],
 "burn": [("ūrō, ūrere", "v3", 0, "")],
 "to buy": [("emō, emere", "v3", 0, "caveat ēmptor — buyer beware!")],
 "to call": [("vocō, vocāre", "v1", 0, "as in vocation — Henle verb")],
 "to carry": [("portō, portāre", "v1", 0, "as in transport — Henle verb")],
 "to catch": [("capiō, capere", "v3io", 0, "as in capture")],
 "to clean": [("pūrgō, pūrgāre", "v1", 0, "as in purge")],
 "to close": [("claudō, claudere", "v3", 0, "as in include, exclude")],
 "to cook": [("coquō, coquere", "v3", 0, "cf. concoct")],
 "cool": [("frīgidulus, -a, -um", "adj12", 0, "slightly cold")],
 "to count": [("numerō, numerāre", "v1", 0, "")],
 "crowd": [("turba, -ae", "f1", 0, "as in turbulent")],
 "to cry": [("fleō, flēre", "v2", 0, "")],
 "to cut": [("secō, secāre", "v1", 0, "as in section, dissect")],
 "to dance": [("saltō, saltāre", "v1", 0, "")],
 "date": [("diēs cōnstitūta", "f5 phrase", 0, "appointed day")],
 "to die": [("morior, morī", "v3io dep", 0, "deponent! as in mortal")],
 "deep": [("profundus, -a, -um", "adj12", 0, "as in profound")],
 "to dig": [("fodiō, fodere", "v3io", 0, "")],
 "to draw": [("dēlīneō, dēlīneāre", "v1", 0, "as in delineate")],
 "to drink": [("bibō, bibere", "v3", 0, "as in imbibe")],
 "to drive": [("gubernō, gubernāre", "v1", 0, "steer — as in govern!")],
 "earth": [("terra, -ae", "f1", 0, "THE Henle/CC first noun — terra firma")],
 "to eat": [("edō, edere", "v3", 0, "as in edible")],
 "energy": [("vīs, vīs", "f3 irr", 0, "force/power — irregular noun")],
 "to exercise": [("exerceō, exercēre", "v2", 0, "")],
 "to explode": [("displōdō, displōdere", "v3", 0, "")],
 "fall": [("autumnus, -ī", "m2", 0, "the season")],
 "to fall (tumble)": [("cadō, cadere", "v3", 0, "as in cascade, decadent")],
 "fan": [("fautor, -ōris", "m3", 0, "supporter — as in favor")],
 "to feed (an animal)": [("pāscō, pāscere", "v3", 0, "as in pasture")],
 "fifth": [("quīntus, -a, -um", "num ord", 0, "the name Quintus!")],
 "to fight": [("pugnō, pugnāre", "v1", 0, "as in pugnacious — Henle verb")],
 "to find": [("inveniō, invenīre", "v4", 0, "as in invent — come upon")],
 "1st": [("prīmus, -a, -um", "num ord", 0, "as in prime")],
 "to fly": [("volō, volāre", "v1", 0, "vs volō, velle = to want!")],
 "to follow": [("sequor, sequī", "v3 dep", 0, "deponent! as in sequence")],
 "foot": [("pēs, pedis", "m3", 0, "as in pedal, pedestrian")],
 "feet": [("pedēs", "m3 pl", 0, "")],
 "fourth": [("quārtus, -a, -um", "num ord", 0, "as in quart")],
 "glass": [("vitrum, -ī", "n2", 0, "cf. vitreous")],
 "to go": [("eō, īre", "v irr", 0, "as in exit — irregular")],
 "to grow": [("crēscō, crēscere", "v3", 0, "as in crescent, crescendo")],
 "to hang up": [("suspendō, suspendere", "v3", 0, "as in suspend")],
 "he": [("is / ille", "pron", 0, "")],
 "to hear": [("audiō, audīre", "v4", 0, "as in audio — Henle verb")],
 "high": [("altus, -a, -um", "adj12", 0, "as in altitude")],
 "i (formal": [("ego", "pron", 0, "as in ego")],
 "instrument": [("organum, -ī", "n2", 0, "musical instrument")],
 "to jump": [("saliō, salīre", "v4", 0, "cf. salient, somersault")],
 "to kill": [("necō, necāre", "v1", 0, "Henle's famous verb")],
 "to kiss": [("bāsiō, bāsiāre", "v1", 0, "Catullus: dā mī bāsia mīlle")],
 "to laugh": [("rīdeō, rīdēre", "v2", 0, "as in ridiculous")],
 "to learn": [("discō, discere", "v3", 0, "root of discipulus")],
 "left": [("sinister, -tra, -trum", "adj12", 0, "yes — that sinister")],
 "leg": [("crūs, crūris", "n3", 0, "")],
 "letter": [("epistula, -ae", "f1", 0, "as in epistle; littera = letter of alphabet")],
 "to lie down (and rest)": [("recumbō, recumbere", "v3", 0, "as in recumbent")],
 "to lift up": [("tollō, tollere", "v3", 0, "principal parts: sustulī, sublātum!")],
 "to lock": [("obserō, obserāre", "v1", 0, "bolt shut")],
 "long (distance": [("longus, -a, -um", "adj12", 0, "")],
 "to lose (someone or something)": [("āmittō, āmittere", "v3", 0, "send away")],
 "to love": [("amō, amāre", "v1", 0, "THE first Latin verb")],
 "low": [("humilis, -e", "adj3", 0, "near the ground — as in humble")],
 "to marry": [("dūcō / nūbō", "v3", 0, "groom dūcit, bride nūbit")],
 "to melt": [("liquēscō, liquēscere", "v3", 0, "as in liquid")],
 "to mix": [("misceō, miscēre", "v2", 0, "as in miscellaneous")],
 "month-long period": [("mēnsis, -is", "m3", 0, "month — cf. semester")],
 "night": [("nox, noctis", "f3", 0, "as in nocturnal")],
 "note": [("adnotātiō, -ōnis", "f3", 0, "as in annotation")],
 "oil": [("oleum, -ī", "n2", 0, "olive oil — cf. petroleum, rock-oil")],
 "old (thing)": [("vetus, -eris", "adj3", 0, "as in veteran")],
 "old": [("senex, senis", "adj3", 0, "of persons — as in senator, senior")],
 "to open": [("aperiō, aperīre", "v4", 0, "as in aperture")],
 "to paint": [("pingō, pingere", "v3", 0, "as in picture")],
 "park": [("viridārium, -ī", "n2", 0, "pleasure-garden")],
 "to pass": [("praetereō, praeterīre", "v irr", 0, "go past")],
 "to pay": [("solvō, solvere", "v3", 0, "settle up — as in solve!")],
 "piece": [("pars, partis", "f3", 0, "as in part")],
 "to play": [("lūdō, lūdere", "v3", 0, "as in ludicrous")],
 "player": [("lūsor, -ōris", "m3", 0, "")],
 "pound": [("lībra, -ae", "f1", 0, "why pound = lb!")],
 "to pray": [("ōrō, ōrāre", "v1", 0, "as in oration — Henle verb")],
 "program": [("prōgramma, -atis", "n3", 0, "Greek loan")],
 "to pull": [("trahō, trahere", "v3", 0, "as in tractor")],
 "to push": [("trūdō, trūdere", "v3", 0, "as in intrude")],
 "race": [("certāmen, -inis", "n3", 0, "contest")],
 "to race": [("certō, certāre", "v1", 0, "")],
 "right": [("dexter, -tra, -trum", "adj12", 0, "as in dexterity")],
 "room": [("conclāve, -is", "n3", 0, "lockable room — as in conclave")],
 "to run": [("currō, currere", "v3", 0, "as in current, curriculum")],
 "second": [("secundus, -a, -um", "num ord", 0, "the one following"),
            ("secundum temporis", "n2 phrase", 1, "the time unit")],
 "to see": [("videō, vidēre", "v2", 0, "as in video — Henle verb")],
 "to sell": [("vendō, vendere", "v3", 0, "as in vendor")],
 "to shake": [("agitō, agitāre", "v1", 0, "as in agitate")],
 "she": [("ea / illa", "pron", 0, "")],
 "to shoot (at)": [("iaculor, iaculārī", "v1 dep", 0, "hurl at — deponent")],
 "short": [("brevis, -e", "adj3", 0, "as in brief"),
           ("curtus, -a, -um", "adj12", 0, "cut short — as in curt")],
 "autograph": [("chīrographum, -ī", "n2", 0, "hand-writing, a real Roman word")],
 "to sing": [("cantō, cantāre", "v1", 0, "as in chant, cantor")],
 "to sit": [("sedeō, sedēre", "v2", 0, "as in sedentary")],
 "to sleep": [("dormiō, dormīre", "v4", 0, "as in dormitory")],
 "to smell": [("olfaciō, olfacere", "v3io", 0, "as in olfactory")],
 "to smile (also laugh)": [("subrīdeō, subrīdēre", "v2", 0, "smile — 'under-laugh'")],
 "to speak": [("loquor, loquī", "v3 dep", 0, "deponent! as in eloquent")],
 "to say": [("dīcō, dīcere", "v3", 0, "as in dictate — Henle verb")],
 "spring": [("vēr, vēris", "n3", 0, "as in vernal")],
 "to stand": [("stō, stāre", "v1", 0, "as in station, statue")],
 "to stop (moving)": [("cōnsistō, cōnsistere", "v3", 0, "")],
 "straight": [("rēctus, -a, -um", "adj12", 0, "as in rectangle, correct")],
 "to swim": [("natō, natāre", "v1", 0, "")],
 "to taste": [("gustō, gustāre", "v1", 0, "as in gusto, disgust")],
 "to teach": [("doceō, docēre", "v2", 0, "as in doctor, docile")],
 "temperature": [("temperātūra, -ae", "f1", 1, "")],
 "thin": [("gracilis, -e", "adj3", 0, "of persons — slender"),
          ("tenuis, -e", "adj3", 0, "of things — as in tenuous")],
 "to think": [("cōgitō, cōgitāre", "v1", 0, "cōgitō ergō sum")],
 "third": [("tertius, -a, -um", "num ord", 0, "as in tertiary")],
 "to throw (e.g. a ball)": [("iaciō, iacere", "v3io", 0, "as in eject, project")],
 "ticket": [("tessera, -ae", "f1", 0, "Roman theater tokens")],
 "tire": [("canthus, -ī", "m2", 0, "classical wheel-rim")],
 "toe": [("digitus pedis", "m2 phrase", 0, "finger of the foot")],
 "to touch": [("tangō, tangere", "v3", 0, "as in tangent, contact")],
 "to turn": [("vertō, vertere", "v3", 0, "as in convert, versus")],
 "to get up": [("surgō, surgere", "v3", 0, "as in surge, resurrection")],
 "to walk": [("ambulō, ambulāre", "v1", 0, "as in ambulance, amble")],
 "to wash": [("lavō, lavāre", "v1", 0, "as in lavatory")],
 "to wear (from the shoulders down)": [("gerō, gerere", "v3", 0, "bear/wear")],
 "to get wet": [("madēscō, madēscere", "v3", 0, "")],
 "to win": [("vincō, vincere", "v3", 0, "vēnī vīdī vīcī")],
 "to work": [("labōrō, labōrāre", "v1", 0, "as in labor — Henle verb")],
 "to write": [("scrībō, scrībere", "v3", 0, "as in scribe, script")],
 "yard": [("virga, -ae", "f1", 1, "rod-measure — 'yard' comes from a rod")],
 "clean": [("mundus, -a, -um", "adj12", 0, "same word as 'world'!")],
}

# ---- Homeschool deck: Henle-1 / CC-style vocab NOT already in the core ----
HS = [
 ("porta, -ae", "gate", "f1", "as in portal"),
 ("nauta, -ae", "sailor", "m1", "masculine 1st decl. — as in nautical"),
 ("agricola, -ae", "farmer", "m1", "masculine 1st decl. — field-tiller"),
 ("poēta, -ae", "poet", "m1", "masculine 1st decl."),
 ("rēgnum, -ī", "kingdom", "n2", "as in reign"),
 ("glōria, -ae", "glory / fame", "f1", ""),
 ("memoria, -ae", "memory", "f1", ""),
 ("victōria, -ae", "victory", "f1", ""),
 ("fortūna, -ae", "fortune / luck", "f1", ""),
 ("sapientia, -ae", "wisdom", "f1", "as in Homō sapiēns"),
 ("iūstitia, -ae", "justice", "f1", ""),
 ("vēritās, -ātis", "truth", "f3", "Harvard's motto"),
 ("lībertās, -ātis", "liberty / freedom", "f3", ""),
 ("virtūs, -ūtis", "courage / virtue", "f3", "manliness, from vir"),
 ("amor, -ōris", "love", "m3", "Rōma spelled backwards"),
 ("deus, -ī / dea, -ae", "god / goddess", "m2/f1", ""),
 ("dominus, -ī / domina, -ae", "master / mistress", "m2/f1", "as in dominate"),
 ("servus, -ī", "slave / servant", "m2", ""),
 ("populus, -ī", "people / nation", "m2", "SPQR: Senātus Populusque Rōmānus"),
 ("gēns, gentis", "clan / tribe", "f3", "as in gentile"),
 ("imperium, -ī", "command / empire", "n2", ""),
 ("lēx, lēgis", "law", "f3", "as in legal"),
 ("cīvis, -is", "citizen", "m/f3", "as in civic"),
 ("senātus, -ūs", "senate", "m4", "council of elders"),
 ("cōnsul, -is", "consul", "m3", "Rome's two chief magistrates"),
 ("gladius, -ī", "sword", "m2", "as in gladiator"),
 ("scūtum, -ī", "shield", "n2", ""),
 ("hasta, -ae", "spear", "f1", ""),
 ("castellum, -ī", "fort", "n2", "as in castle"),
 ("aquila, -ae", "eagle", "f1", "the legion's standard"),
 ("lupus, -ī / lupa, -ae", "wolf / she-wolf", "m2/f1", "the she-wolf raised Romulus & Remus"),
 ("Rōma, -ae", "Rome", "f1", "the Eternal City"),
 ("nōmen, -inis", "name", "n3", "as in nominate"),
 ("via, -ae", "road / way", "f1", "also street in the core deck"),
 ("terra, -ae", "land / earth", "f1", "also in the core deck — THE first noun"),
 ("sum, esse", "to be", "v irr", "sum es est sumus estis sunt"),
 ("possum, posse", "to be able", "v irr", "as in possible"),
 ("dō, dare", "to give", "v1", "as in donate, data"),
 ("habeō, habēre", "to have", "v2", "as in habit"),
 ("teneō, tenēre", "to hold", "v2", "as in tenant, contain"),
 ("moveō, movēre", "to move", "v2", ""),
 ("mittō, mittere", "to send", "v3", "as in mission, transmit"),
 ("dūcō, dūcere", "to lead", "v3", "as in duke, conduct"),
 ("faciō, facere", "to make / do", "v3io", "as in factory, fact"),
 ("veniō, venīre", "to come", "v4", "as in advent, convene"),
 ("sciō, scīre", "to know", "v4", "as in science"),
 ("timeō, timēre", "to fear", "v2", "as in timid"),
 ("spērō, spērāre", "to hope", "v1", "dum spīrō spērō — while I breathe, I hope"),
 ("servō, servāre", "to guard / save", "v1", "as in conserve"),
 ("nāvigō, nāvigāre", "to sail", "v1", "as in navigate"),
 ("parō, parāre", "to prepare", "v1", "semper parātus — always ready"),
 ("superō, superāre", "to overcome", "v1", "as in superior"),
 ("et", "and", "conj", ""),
 ("sed", "but", "conj", ""),
 ("nōn", "not", "adv", ""),
 ("semper", "always", "adv", ""),
 ("numquam", "never", "adv", ""),
 ("saepe", "often", "adv", ""),
 ("cum", "with (+ abl.)", "prep", ""),
 ("in", "in, on (+ abl.) / into (+ acc.)", "prep", ""),
 ("ad", "to, toward (+ acc.)", "prep", ""),
 ("ex, ē", "out of (+ abl.)", "prep", "as in exit"),
 ("ab, ā", "from, by (+ abl.)", "prep", ""),
 ("per", "through (+ acc.)", "prep", "as in perennial"),
 ("post", "after (+ acc.)", "prep", "as in postpone"),
 ("ante", "before (+ acc.)", "prep", "as in antebellum"),
 ("sub", "under (+ abl.)", "prep", "as in submarine"),
 ("inter", "between, among (+ acc.)", "prep", "as in international"),
 ("contrā", "against (+ acc.)", "prep", "as in contrary"),
 ("dē", "down from, about (+ abl.)", "prep", "as in descend"),
 ("quis? quid?", "who? what?", "pron", ""),
 ("cūr?", "why?", "adv", ""),
 ("ubi?", "where? when?", "adv", "as in ubiquitous"),
]

# ---- Phrases & mottos deck ----
PH = [
 ("carpe diem", "seize the day", "Horace"),
 ("ē plūribus ūnum", "out of many, one", "on U.S. coins"),
 ("semper fidēlis", "always faithful", "USMC motto"),
 ("vēnī, vīdī, vīcī", "I came, I saw, I conquered", "Julius Caesar"),
 ("cōgitō, ergō sum", "I think, therefore I am", "Descartes"),
 ("ad astra per aspera", "to the stars through hardships", "Kansas motto"),
 ("mea culpa", "my fault", ""),
 ("et cetera", "and the rest", "etc.!"),
 ("ante merīdiem / post merīdiem", "before / after midday", "a.m. and p.m.!"),
 ("annō Dominī", "in the year of the Lord", "A.D.!"),
 ("alma māter", "nourishing mother", "your school"),
 ("bonā fidē", "in good faith", ""),
 ("terra firma", "solid ground", ""),
 ("tempus fugit", "time flies", "Virgil"),
 ("caveat ēmptor", "let the buyer beware", ""),
 ("in tōtō", "entirely", ""),
 ("per sē", "by itself", ""),
 ("vice versā", "the other way around", ""),
 ("dum spīrō, spērō", "while I breathe, I hope", "S. Carolina motto"),
 ("ora et labōrā", "pray and work", "Benedictine motto"),
]

# ---- Chants deck (CC-style paradigm memory work) ----
CH = [
 ("1st declension endings (sg)", "-a, -ae, -ae, -am, -ā", "nom gen dat acc abl — puella"),
 ("1st declension endings (pl)", "-ae, -ārum, -īs, -ās, -īs", "nom gen dat acc abl — puellae"),
 ("2nd declension m. endings (sg)", "-us, -ī, -ō, -um, -ō", "nom gen dat acc abl — servus"),
 ("2nd declension m. endings (pl)", "-ī, -ōrum, -īs, -ōs, -īs", "nom gen dat acc abl — servī"),
 ("2nd declension n. endings (sg)", "-um, -ī, -ō, -um, -ō", "nom gen dat acc abl — bellum"),
 ("2nd declension n. endings (pl)", "-a, -ōrum, -īs, -a, -īs", "nom gen dat acc abl — bella"),
 ("3rd declension endings (sg)", "—, -is, -ī, -em, -e", "nom gen dat acc abl — rēx"),
 ("3rd declension endings (pl)", "-ēs, -um, -ibus, -ēs, -ibus", "nom gen dat acc abl — rēgēs"),
 ("present tense endings", "-ō, -s, -t, -mus, -tis, -nt", "I, you, he/she, we, y'all, they"),
 ("amō (present)", "amō, amās, amat, amāmus, amātis, amant", "1st conjugation model"),
 ("sum (present)", "sum, es, est, sumus, estis, sunt", "to be — irregular"),
 ("imperfect endings", "-bam, -bās, -bat, -bāmus, -bātis, -bant", "was/used to ___"),
 ("future endings (1st/2nd conj.)", "-bō, -bis, -bit, -bimus, -bitis, -bunt", "will ___"),
 ("the five cases", "nōminātīve, genitive, dative, accūsātive, ablātive", "naming, of, to/for, direct object, by/with/from"),
]


def main():
    src = json.load(open(SRC))
    remaining = {k: list(v) for k, v in M.items()}
    cards, errors = [], []
    for i, w in enumerate(src):
        en = w['en']
        if en not in remaining or not remaining[en]:
            errors.append(f"NO TRANSLATION LEFT for #{i} {en!r}")
            continue
        la, gram, neo, note = remaining[en].pop(0)
        c = {"id": f"c{i:03d}", "en": en, "la": la, "gram": gram, "deck": "core"}
        if neo: c["neo"] = 1
        if note: c["note"] = note
        cards.append(c)
    leftovers = {k: v for k, v in remaining.items() if v}
    if leftovers: errors.append(f"UNCONSUMED translations: {leftovers}")
    if errors:
        print("\n".join(errors)); sys.exit(1)

    for j, (la, en, gram, note) in enumerate(HS):
        c = {"id": f"h{j:03d}", "en": en, "la": la, "gram": gram, "deck": "homeschool"}
        if note: c["note"] = note
        cards.append(c)
    for j, (la, en, note) in enumerate(PH):
        c = {"id": f"p{j:03d}", "en": en, "la": la, "gram": "phrase", "deck": "phrases"}
        if note: c["note"] = note
        cards.append(c)
    for j, (front, back, note) in enumerate(CH):
        c = {"id": f"x{j:03d}", "en": front, "la": back, "gram": "chant", "deck": "chants"}
        if note: c["note"] = note
        cards.append(c)

    # oracles
    assert len([c for c in cards if c['deck'] == 'core']) == len(src), "core count mismatch"
    assert len({c['id'] for c in cards}) == len(cards), "duplicate ids"
    for c in cards:
        assert c['la'].strip() and c['en'].strip(), f"empty field in {c}"

    out = os.path.join(HERE, 'data', 'words.json')
    json.dump(cards, open(out, 'w'), ensure_ascii=False, indent=1)
    n = lambda d: len([c for c in cards if c['deck'] == d])
    print(f"OK: {len(cards)} cards -> {out}  (core={n('core')} homeschool={n('homeschool')} phrases={n('phrases')} chants={n('chants')})")

if __name__ == '__main__':
    main()
